Repository octokit/octokit.rb, pull requests merged in 2022-10, with the labels that each got.

#1495 Remove Octokit::Client::Hooks#available_hooks
  lib/octokit/client/hooks.rb
  spec/octokit/client/hooks_spec.rb
Labels: breaking change, housekeeping

#980 Change the default value of `update_ref` `force` to false
  lib/octokit/client/refs.rb
Labels: breaking change, v5 release

#1494 Remove Octokit::Client::Authorizations
  .rubocop_todo.yml
  lib/octokit/client.rb
  lib/octokit/client/authorizations.rb
  lib/octokit/client/tokens.rb
  spec/cassettes/Octokit_Client_Authorizations/_authorization/returns_a_single_authorization.json
  spec/cassettes/Octokit_Client_Authorizations/_authorizations/lists_existing_authorizations.json
  spec/cassettes/Octokit_Client_Authorizations/_create_authorization/with_idempotent_true/creates_a_new_authorization_with_fingerprint.json
  spec/cassettes/Octokit_Client_Authorizations/_create_authorization/with_idempotent_true/creates_a_new_authorization_with_options.json
  spec/cassettes/Octokit_Client_Authorizations/_create_authorization/with_idempotent_true/returns_an_existing_API_authorization_if_one_already_exists.json
  spec/cassettes/Octokit_Client_Authorizations/_create_authorization/without_idempotent_true/creates_a_new_API_authorization_each_time.json
  spec/cassettes/Octokit_Client_Authorizations/_create_authorization/without_idempotent_true/creates_a_new_authorization_with_options.json
  spec/cassettes/Octokit_Client_Authorizations/_create_authorization/without_idempotent_true/creates_an_API_authorization.json
  spec/cassettes/Octokit_Client_Authorizations/_delete_authorization/deletes_an_existing_authorization.json
  spec/cassettes/Octokit_Client_Authorizations/_update_authorization/updates_and_existing_authorization.json
  spec/cassettes/Octokit_Client_Tokens/_scopes/checks_the_scopes_on_a_one-off_token.json
  spec/cassettes/Octokit_Client_Tokens/_scopes/checks_the_scopes_on_the_current_token.json
  spec/octokit/client/authorizations_spec.rb
  spec/octokit/client/tokens_spec.rb
Labels: housekeeping
