Repository octokit/octokit.rb, pull requests merged in 2022-06, with the labels that each got.

#1428 Reverts autoloading of modules change
  lib/octokit.rb
  lib/octokit/client.rb
Labels: bug, breaking change

#1446 Adds details on how to run a manual file integrity check
  RELEASE.md
  script/package
  script/release
  script/validate
Labels: docs-and-samples

#1445 Suppress various warnings
  lib/octokit/client.rb
  lib/octokit/client/pub_sub_hubbub.rb
  lib/octokit/connection.rb
  spec/helper.rb
  spec/octokit/client/actions_secrets_spec.rb
  spec/octokit/client/actions_workflow_runs_spec.rb
  spec/octokit/client/apps_spec.rb
  spec/octokit/client/hooks_spec.rb
  spec/octokit/client/organizations_spec.rb
  spec/octokit/client/rate_limit_spec.rb
  spec/octokit/client/releases_spec.rb
  spec/octokit/client/repositories_spec.rb
  spec/octokit/client/stats_spec.rb
  spec/octokit/client_spec.rb
  spec/octokit/enterprise_admin_client/search_indexing_spec.rb
  spec/octokit/enterprise_admin_client/users_spec.rb
  spec/octokit/enterprise_management_console_client/management_console_spec.rb
Labels: improvement
