Repository octokit/octokit.rb, pull requests merged in 2022-05, with the labels that each got.

#1121 Fix service status methods. Fixes #1107
  lib/octokit/client/service_status.rb
  spec/cassettes/Octokit_Client_ServiceStatus/_github_status/returns_the_current_system_status.json
  spec/cassettes/Octokit_Client_ServiceStatus/_github_status/returns_the_most_recent_status_messages.json
  spec/cassettes/Octokit_Client_ServiceStatus/_github_status_last_message/returns_the_last_human_message.json
  spec/cassettes/Octokit_Client_ServiceStatus/_github_status_messages/returns_the_most_recent_status_messages.json
  spec/cassettes/Octokit_Client_ServiceStatus/_github_status_summary/returns_the_current_system_status_summary.json
  spec/octokit/client/service_status_spec.rb
Labels: breaking change, improvement

#1375 [fix] Escape `ref` in `archive_link`
  lib/octokit/client/contents.rb
  spec/octokit/client/contents_spec.rb
Labels: bug

#1415 Fix checks pagination
  lib/octokit/client/checks.rb
  spec/cassettes/Octokit_Client_Checks/_check_run_annotations/auto-paginates_the_results.json
  spec/cassettes/Octokit_Client_Checks/_check_run_annotations/paginates_the_results.json
  spec/cassettes/Octokit_Client_Checks/_check_runs_for_check_suite/auto-paginates_the_results.json
  spec/cassettes/Octokit_Client_Checks/_check_runs_for_check_suite/paginates_the_results.json
  spec/cassettes/Octokit_Client_Checks/_check_runs_for_ref/auto-paginates_the_results.json
  spec/cassettes/Octokit_Client_Checks/_check_runs_for_ref/paginates_the_results.json
  spec/cassettes/Octokit_Client_Checks/_check_suites_for_ref/auto-paginates_the_results.json
  spec/cassettes/Octokit_Client_Checks/_check_suites_for_ref/paginates_the_results.json
  spec/octokit/client/checks_spec.rb
Labels: bug

#1419 Ensures that any nil parameters being passed in will initalize with Octokit's defaults instead of nil
  lib/octokit/client.rb
  spec/octokit/client_spec.rb
Labels: bug

#1411 Allow Faraday v2 usage
  .github/workflows/octokit.yml
  Gemfile
  README.md
  lib/octokit/authentication.rb
  lib/octokit/client.rb
  lib/octokit/client/pub_sub_hubbub.rb
  lib/octokit/connection.rb
  lib/octokit/default.rb
  lib/octokit/response/base_middleware.rb
  lib/octokit/response/feed_parser.rb
  lib/octokit/response/raise_error.rb
  lib/octokit/warnable.rb
  octokit.gemspec
  spec/helper.rb
Labels: improvement
