Repository octokit/octokit.rb, pull requests merged in 2023-01, with the labels that each got.

#1511 Adds a stale action to clean up old PRs/Issues
  .github/workflows/stale.yaml
Labels: Priority: Normal, Type: Maintenance

#1512 Add using GitHub app authentication in README
  README.md
Labels: Type: Documentation

#1513 Fix missing and broken links in README table of contents
  README.md
Labels: Type: Documentation

#1529 Repository: Fix issue with fragment identifier in branch name
  lib/octokit/client/repositories.rb
  spec/cassettes/Octokit_Client_Repositories/_branches/returns_a_single_branch_that_includes_character_that_needs_to_be_escaped.json
  spec/octokit/client/repositories_spec.rb
Labels: Type: Bug
